"""
Playwright test suite for LambdaTest Ecommerce Playground — generated by Agentic STLC pipeline. Do not edit manually.
"""
import pytest
from playwright.sync_api import expect

@pytest.mark.scenario("SC-001")
@pytest.mark.requirement("AC-001")
def test_sc_001_searched_for_products_on_ecommerce_playground_lamb(page):
    """SC-001: searched for products on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=28")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    add_btn = page.locator("#button-cart")
    add_btn.wait_for(timeout=15000)
    add_btn.click()
    page.wait_for_timeout(1500)
    cart_indicator = page.locator("#cart button span, #cart-total")
    assert cart_indicator.count() > 0, "Cart indicator not found after adding product"

@pytest.mark.scenario("SC-002")
@pytest.mark.requirement("AC-002")
def test_sc_002_attempted_to_open_the_cart_and_select_a_product_op(page):
    """SC-002: attempted to open the cart and select a product option on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=28")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    page.locator("#button-cart").wait_for(timeout=15000)
    page.locator("#button-cart").click()
    page.wait_for_timeout(1500)
    cart_btn = page.locator("#cart > button")
    cart_btn.wait_for(timeout=10000)
    cart_btn.click()
    page.wait_for_timeout(1000)
    cart_items = page.locator("#cart .text-left a")
    cart_items.first.wait_for(timeout=10000)
    assert cart_items.count() > 0, "No items visible in cart dropdown"

@pytest.mark.scenario("SC-003")
@pytest.mark.requirement("AC-003")
def test_sc_003_opened_the_laptops_product_catalog_on_ecommerce_pl(page):
    """SC-003: opened the Laptops product catalog on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=18")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    products = page.locator(".product-thumb")
    products.first.wait_for(timeout=15000)
    assert products.count() > 0, "No products visible in the Laptops catalog"

@pytest.mark.scenario("SC-004")
@pytest.mark.requirement("AC-004")
def test_sc_004_attempted_to_filter_components_by_apple_on_ecommer(page):
    """SC-004: attempted to filter Components by Apple on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=25")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    filter_link = page.locator("#column-left .list-group-item").filter(has_text="Apple")
    if filter_link.count() == 0:
        filter_link = page.locator("#column-left a").filter(has_text="Apple")
    filter_link.first.wait_for(timeout=15000)
    filter_link.first.click()
    page.wait_for_load_state("domcontentloaded", timeout=15000)
    assert page.locator("#content").count() > 0, "Content area not visible after applying filter"

@pytest.mark.scenario("SC-005")
@pytest.mark.requirement("AC-005")
def test_sc_005_opened_a_product_detail_page_on_ecommerce_playgrou(page):
    """SC-005: opened a product detail page on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/index.php?route=product/product&product_id=28")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    product_name = page.locator("h1").first
    product_name.wait_for(timeout=15000)
    assert product_name.inner_text().strip() != "", "Product name is empty on detail page"
    price = page.locator(".price-new, h2.price, .price").first
    price.wait_for(timeout=10000)
    assert price.count() > 0, "Product price not visible on detail page"

@pytest.mark.scenario("SC-006")
@pytest.mark.requirement("AC-006")
def test_sc_006_browsed_the_homepage_and_product_listings_on_ecomm(page):
    """SC-006: browsed the homepage and product listings on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    hero = page.locator("#content, .slideshow0, .swiper-wrapper, .carousel-inner").first
    hero.wait_for(timeout=15000)
    assert hero.count() > 0, "Homepage content not visible without login"
    assert page.title().strip() != "", "Page title is empty"

@pytest.mark.scenario("SC-007")
@pytest.mark.requirement("AC-007")
def test_sc_007_searched_for_an_iphone_on_ecommerce_playground_lam(page):
    """SC-007: searched for an iPhone on ecommerce-playground.lambdatest.io."""
    page.goto("https://ecommerce-playground.lambdatest.io/")
    page.wait_for_load_state("domcontentloaded", timeout=30000)
    search_input = page.locator("input[name='search']")
    search_input.wait_for(timeout=15000)
    search_input.fill("iPhone")
    search_input.press("Enter")
    page.wait_for_load_state("domcontentloaded", timeout=20000)
    results = page.locator(".product-thumb")
    results.first.wait_for(timeout=15000)
    assert results.count() > 0, "No search results returned for 'iPhone'"
