# AUTO-GENERATED by Agentic STLC Platform — DO NOT EDIT
# Generated at: 2026-05-13T23:38:53.423057+00:00
# Source: scenarios/scenarios.json

import pytest
import os


TARGET_URL = os.environ.get("TARGET_URL", 'https://ecommerce-playground.lambdatest.io/')


@pytest.mark.scenario("SC-001")
@pytest.mark.requirement("AC-001")
def test_sc_001(page, target_url=TARGET_URL):
    """[SC-001] User can add a product to the cart from the product detail page and see the cart"""
    page.goto(target_url)
    page.wait_for_load_state("networkidle")
    product = page.locator(".product-thumb a, .product-layout a").first
    product.click()
    page.wait_for_load_state("networkidle")
    add_btn = page.locator("#button-cart, button[id*='cart'], .btn-cart")
    add_btn.click()
    page.wait_for_load_state("networkidle")
    cart_indicator = page.locator("#cart-total, .cart-total, #cart button")
    assert cart_indicator.is_visible(), "Cart did not update after adding product"


@pytest.mark.scenario("SC-002")
@pytest.mark.requirement("AC-002")
def test_sc_002(page, target_url=TARGET_URL):
    """[SC-002] User can open the cart dropdown and see the list of added items with their names"""
    page.goto(target_url)
    page.wait_for_load_state("networkidle")
    product = page.locator(".product-thumb a, .product-layout a").first
    product.click()
    page.wait_for_load_state("networkidle")
    add_btn = page.locator("#button-cart, button[id*='cart'], .btn-cart")
    add_btn.click()
    page.wait_for_load_state("networkidle")
    cart_indicator = page.locator("#cart-total, .cart-total, #cart button")
    assert cart_indicator.is_visible(), "Cart did not update after adding product"


@pytest.mark.scenario("SC-003")
@pytest.mark.requirement("AC-003")
def test_sc_003(page, target_url=TARGET_URL):
    """[SC-003] User can navigate to the Laptops product catalog and see a grid of product listi"""
    page.goto(target_url + "index.php?route=product/category&path=20")
    page.wait_for_load_state("networkidle")
    products = page.locator(".product-thumb, .product-layout")
    assert products.count() > 0, "Category page shows no products"


@pytest.mark.scenario("SC-004")
@pytest.mark.requirement("AC-004")
def test_sc_004(page, target_url=TARGET_URL):
    """[SC-004] User can apply a manufacturer brand filter from the sidebar to narrow product re"""
    page.goto(target_url + "index.php?route=product/category&path=20")
    page.wait_for_load_state("networkidle")
    filter_el = page.locator(".list-group-item, .filter-group input[type='checkbox']").first
    if filter_el.is_visible():
        filter_el.click()
        page.wait_for_load_state("networkidle")
    products = page.locator(".product-thumb, .product-layout")
    assert products.count() >= 0, "Filter interaction caused page error"


@pytest.mark.scenario("SC-005")
@pytest.mark.requirement("AC-005")
def test_sc_005(page, target_url=TARGET_URL):
    """[SC-005] User can click a product thumbnail to open its detail page and see the product n"""
    assert page.title().strip() != "", "Page failed to load"


@pytest.mark.scenario("SC-006")
@pytest.mark.requirement("AC-006")
def test_sc_006(page, target_url=TARGET_URL):
    """[SC-006] User can browse the homepage and product listings without logging in as a guest"""
    page.goto(target_url + "index.php?route=product/category&path=20")
    page.wait_for_load_state("networkidle")
    products = page.locator(".product-thumb, .product-layout")
    assert products.count() > 0, "Category page shows no products"


@pytest.mark.scenario("SC-007")
@pytest.mark.requirement("AC-007")
def test_sc_007(page, target_url=TARGET_URL):
    """[SC-007] User can search for a product by name using the search bar and see relevant resu"""
    page.goto(target_url)
    search_box = page.locator("input[name='search'], input[type='search'], #search")
    search_box.fill("laptop")
    search_box.press("Enter")
    page.wait_for_load_state("networkidle")
    results = page.locator(".product-thumb, .product-layout, article.product-card")
    assert results.count() > 0, "No search results returned for 'laptop'"


@pytest.mark.scenario("SC-008")
@pytest.mark.requirement("AC-008")
def test_sc_008(page, target_url=TARGET_URL):
    """[SC-008] User can register a new account by filling in first name last name email telepho"""
    page.goto(target_url + "index.php?route=account/login")
    page.wait_for_load_state("networkidle")
    assert page.locator("#input-email, input[name='email']").is_visible(), "Email field not visible on login page"
    assert page.locator("#input-password, input[name='password']").is_visible(), "Password field not visible"


@pytest.mark.scenario("SC-009")
@pytest.mark.requirement("AC-009")
def test_sc_009(page, target_url=TARGET_URL):
    """[SC-009] User can log in with a registered email address and password and land on the acc"""
    page.goto(target_url + "index.php?route=account/login")
    page.wait_for_load_state("networkidle")
    assert page.locator("#input-email, input[name='email']").is_visible(), "Email field not visible on login page"
    assert page.locator("#input-password, input[name='password']").is_visible(), "Password field not visible"


@pytest.mark.scenario("SC-010")
@pytest.mark.requirement("AC-010")
def test_sc_010(page, target_url=TARGET_URL):
    """[SC-010] User can log out from the account and be redirected to the home page"""
    assert page.title().strip() != "", "Page failed to load"


@pytest.mark.scenario("SC-011")
@pytest.mark.requirement("AC-011")
def test_sc_011(page, target_url=TARGET_URL):
    """[SC-011] User can remove an item from the shopping cart and see the cart update with the """
    page.goto(target_url)
    page.wait_for_load_state("networkidle")
    product = page.locator(".product-thumb a, .product-layout a").first
    product.click()
    page.wait_for_load_state("networkidle")
    add_btn = page.locator("#button-cart, button[id*='cart'], .btn-cart")
    add_btn.click()
    page.wait_for_load_state("networkidle")
    cart_indicator = page.locator("#cart-total, .cart-total, #cart button")
    assert cart_indicator.is_visible(), "Cart did not update after adding product"


@pytest.mark.scenario("SC-012")
@pytest.mark.requirement("AC-012")
def test_sc_012(page, target_url=TARGET_URL):
    """[SC-012] User can update the quantity of an item in the shopping cart and see the line to"""
    page.goto(target_url)
    page.wait_for_load_state("networkidle")
    product = page.locator(".product-thumb a, .product-layout a").first
    product.click()
    page.wait_for_load_state("networkidle")
    add_btn = page.locator("#button-cart, button[id*='cart'], .btn-cart")
    add_btn.click()
    page.wait_for_load_state("networkidle")
    cart_indicator = page.locator("#cart-total, .cart-total, #cart button")
    assert cart_indicator.is_visible(), "Cart did not update after adding product"


@pytest.mark.scenario("SC-013")
@pytest.mark.requirement("AC-013")
def test_sc_013(page, target_url=TARGET_URL):
    """[SC-013] User can sort products by price low to high and see the listing order change"""
    page.goto(target_url + "index.php?route=checkout/checkout")
    page.wait_for_load_state("networkidle")
    assert page.locator("#checkout-checkout, .panel-checkout").first.is_visible() or \
           page.locator("#cart-total, #cart").first.is_visible(), "Checkout page did not load"


@pytest.mark.scenario("SC-014")
@pytest.mark.requirement("AC-014")
def test_sc_014(page, target_url=TARGET_URL):
    """[SC-014] User can add a product to the wish list from the product detail page and view it"""
    page.goto(target_url)
    page.wait_for_load_state("networkidle")
    product_link = page.locator(".product-thumb a, h4 a").first
    product_link.click()
    page.wait_for_load_state("networkidle")
    assert page.locator("h1, h2.page-title").first.is_visible(), "Product title not visible on PDP"
    assert page.locator("#button-cart, .btn-cart").first.is_visible(), "Add to Cart button not visible"


@pytest.mark.scenario("SC-015")
@pytest.mark.requirement("AC-015")
def test_sc_015(page, target_url=TARGET_URL):
    """[SC-015] User can complete a guest checkout by entering a shipping address and selecting """
    page.goto(target_url + "index.php?route=checkout/checkout")
    page.wait_for_load_state("networkidle")
    assert page.locator("#checkout-checkout, .panel-checkout").first.is_visible() or \
           page.locator("#cart-total, #cart").first.is_visible(), "Checkout page did not load"

