"""
Selenium test suite for LambdaTest eCommerce playground browsing and search.
Generated by pure CI pipeline. Do not edit manually.
Each test maps to one acceptance criterion in requirements/search.txt.
"""

import pytest
from selenium.webdriver.support.ui import WebDriverWait
from tests.selenium.pages.products_page import ProductsPage

@pytest.mark.scenario("SC-001")
@pytest.mark.requirement("AC-001")
def test_sc_001_navigate_to_products_and_view_list(driver):
    """SC-001: Navigate to product section and view available product list."""
    page = ProductsPage(driver)
    page.navigate_to_products_page()

    assert "product" in page.current_url().lower() or "shop" in page.current_url().lower()
    product_tiles = page.get_product_tiles()
    assert len(product_tiles) > 0

@pytest.mark.scenario("SC-002")
@pytest.mark.requirement("AC-002")
def test_sc_002_filter_products_by_category(driver):
    """SC-002: Filter products by category."""
    page = ProductsPage(driver)
    page.navigate_to_products_page()

    filter_names = ["Apple", "Samsung", "HTC", "Canon", "Nikon", "Phones", "Laptops"]
    applied = False
    for name in filter_names:
        if page.apply_filter(name):
            applied = True
            break
    assert applied
    assert len(page.get_product_tiles()) > 0

@pytest.mark.scenario("SC-003")
@pytest.mark.requirement("AC-003")
def test_sc_003_click_product_view_details(driver):
    """SC-003: Click a product to view details."""
    page = ProductsPage(driver)
    page.navigate_to_products_page()

    initial_url = page.current_url()
    assert page.click_first_product_details()
    
    WebDriverWait(driver, 15).until(
        lambda d: d.current_url != initial_url or len(page.get_product_details_elements()) > 0
    )
    assert len(page.get_product_details_elements()) > 0

@pytest.mark.scenario("SC-004")
@pytest.mark.requirement("AC-004")
def test_sc_004_product_highlights_visible_without_login(driver):
    """SC-004: View product highlights without logging in."""
    page = ProductsPage(driver)
    page.navigate_to_products_page()

    assert not page.is_login_gate_present()
    assert page.has_guest_browsing_content()

@pytest.mark.scenario("SC-005")
@pytest.mark.requirement("AC-005")
def test_sc_005_relevant_results_for_selected_filter(driver):
    """SC-005: Search results are relevant to selected filters or criteria."""
    # Scenario SC-005 handled by Kane AI Scripting Agent
    page = ProductsPage(driver)
    page.navigate_to_products_page()
    # Objective: User receives relevant results based on selected filters or search criteria

@pytest.mark.scenario("SC-006")
@pytest.mark.requirement("AC-006")
def test_sc_006_search_for_iphone_products_and_view_results(driver):
    """SC-006: Search for iPhone products and view results."""
    # Scenario SC-006 handled by Kane AI Scripting Agent
    page = ProductsPage(driver)
    page.navigate_to_products_page()
    # Objective: User can search for "iphone" in the search bar

@pytest.mark.scenario("SC-007")
@pytest.mark.requirement("AC-007")
def test_sc_007_search_for_iphone_17_products_and_view_results(driver):
    """SC-007: Search for iPhone 17 products and view results."""
    # Scenario SC-007 handled by Kane AI Scripting Agent
    page = ProductsPage(driver)
    page.navigate_to_products_page()
    # Objective: User can search for "iPhone 17 Pro" using the top search bar

@pytest.mark.scenario("SC-008")
@pytest.mark.requirement("AC-008")
def test_sc_008_add_product_to_cart_and_verify_in_cart(driver):
    """SC-008: Add product to cart and verify in cart."""
    # Scenario SC-008 handled by Kane AI Scripting Agent
    page = ProductsPage(driver)
    page.navigate_to_products_page()
    # Objective: User can add a product to the cart from the product listing page