"""
Selenium test suite for LambdaTest eCommerce playground.
Generated by CI pipeline. Do not edit manually.
"""

import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

@pytest.mark.scenario("SC-001")
@pytest.mark.requirement("AC-001")
def test_sc_001_navigate_to_products_and_view_list(driver):
    """SC-001: Navigated to Shop and saw 12 product tiles."""
    driver.get("https://ecommerce-playground.lambdatest.io/")
    wait = WebDriverWait(driver, 20)
    nav_link = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//nav//a[contains(@href, 'category') or contains(translate(text(),'SHOP','shop'),'shop')]"))
    )
    nav_link.click()
    products = wait.until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb, .product-layout"))
    )
    assert len(products) > 0, "No products found on catalog page"

@pytest.mark.scenario("SC-002")
@pytest.mark.requirement("AC-002")
def test_sc_002_filter_products_by_category(driver):
    """SC-002: Applied Apple filter, 3 products shown."""
    driver.get("https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=20")
    wait = WebDriverWait(driver, 20)
    apple_filter = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//label[contains(., 'Apple')] | //a[contains(., 'Apple') and ancestor::*[contains(@class,'sidebar') or contains(@class,'filter') or contains(@class,'mz-filter')]]"))
    )
    apple_filter.click()
    products = wait.until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb, .product-layout"))
    )
    assert len(products) > 0, "No products after applying Apple filter"
