"""
Selenium test suite for LambdaTest eCommerce playground.
Generated by CI pipeline. Do not edit manually.
"""

import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

@pytest.mark.scenario("SC-001")
@pytest.mark.requirement("AC-001")
def test_sc_001_navigate_to_products_and_view_list(driver):
    """SC-001: Navigate to product catalog and view product list."""
    driver.get("https://ecommerce-playground.lambdatest.io/")
    wait = WebDriverWait(driver, 20)
    nav_link = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//nav//a[contains(@href, 'category') or contains(translate(text(),'SHOP','shop'),'shop')]"))
    )
    nav_link.click()
    products = wait.until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb, .product-layout"))
    )
    assert len(products) > 0, "No products found on catalog page"

@pytest.mark.scenario("SC-002")
@pytest.mark.requirement("AC-002")
def test_sc_002_filter_products_by_category(driver):
    """SC-002: Apply a brand filter to narrow product results."""
    driver.get("https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=20")
    wait = WebDriverWait(driver, 20)
    apple_filter = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//label[contains(., 'Apple')] | //a[contains(., 'Apple') and ancestor::*[contains(@class,'sidebar') or contains(@class,'filter') or contains(@class,'mz-filter')]]"))
    )
    apple_filter.click()
    products = wait.until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb, .product-layout"))
    )
    assert len(products) > 0, "No products after applying Apple filter"

@pytest.mark.scenario("SC-003")
@pytest.mark.requirement("AC-003")
def test_sc_003_click_product_view_details(driver):
    """SC-003: Click a product to view its detail page."""
    driver.get("https://ecommerce-playground.lambdatest.io/index.php?route=product/category&path=20")
    wait = WebDriverWait(driver, 30)
    product_link = wait.until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, ".product-thumb h4 a, .product-thumb .caption a"))
    )
    product_link.click()
    name = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "h1, h2.product-title")))
    price = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".price, [class*='price']")))
    assert name.text.strip(), "Product name is empty on detail page"
    assert price.text.strip(), "Product price is empty on detail page"

@pytest.mark.scenario("SC-004")
@pytest.mark.requirement("AC-004")
def test_sc_004_product_highlights_visible_without_login(driver):
    """SC-004: Browse products and homepage without logging in."""
    driver.get("https://ecommerce-playground.lambdatest.io/")
    wait = WebDriverWait(driver, 20)
    items = wait.until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb, .product-layout, .carousel-item img"))
    )
    assert len(items) > 0, "No products or featured items visible on homepage without login"

@pytest.mark.scenario("SC-005")
@pytest.mark.requirement("AC-005")
def test_sc_005_relevant_results_for_selected_filter(driver):
    """SC-005: Search for a product by name and see relevant results."""
    driver.get("https://ecommerce-playground.lambdatest.io/")
    wait = WebDriverWait(driver, 20)
    search_box = wait.until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, "input[name='search'], #search input[type='text']"))
    )
    search_box.clear()
    search_box.send_keys("iPhone")
    search_box.submit()
    results = wait.until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb, .product-layout"))
    )
    assert len(results) > 0, "No results found when searching for iPhone"
