#!/usr/bin/env python3
"""
Agentic STLC Orchestrator — Stages 2-5.
Fully deterministic: no LLM required.
"""
import asyncio
import json
import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import httpx
from mcp import ClientSession
from mcp.client.sse import sse_client

# ── Runtime config ─────────────────────────────────────────────────────────
MCP_URL           = "https://mcp.lambdatest.com/mcp"
LT_USERNAME       = os.environ.get("LT_USERNAME", "")
LT_ACCESS_KEY     = os.environ.get("LT_ACCESS_KEY", "")
FULL_RUN          = os.environ.get("FULL_RUN", "true").lower() == "true"
TARGET_URL        = "https://ecommerce-playground.lambdatest.io/"
TODAY             = datetime.now(timezone.utc).date().isoformat()
RUN_NUMBER        = os.environ.get("GITHUB_RUN_NUMBER", "")
BUILD_NAME        = (
    f"Agentic STLC #{RUN_NUMBER} | {TODAY}" if RUN_NUMBER
    else f"Agentic STLC | {TODAY}"
)

JOB_ID_RE = re.compile(r"jobId=([\w-]+)")

# ── Deterministic test generation ──────────────────────────────────────────
FUNCTION_NAMES = {
    "SC-001": "test_sc_001_navigate_to_products_and_view_list",
    "SC-002": "test_sc_002_filter_products_by_category",
    "SC-003": "test_sc_003_click_product_view_details",
    "SC-004": "test_sc_004_product_highlights_visible_without_login",
    "SC-005": "test_sc_005_relevant_results_for_selected_filter",
}

TEST_HEADER = '''\
"""
Selenium test suite — generated by Agentic STLC pipeline. Do not edit manually.
"""
import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

'''

SELENIUM_BODIES = {
    "SC-001": '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 20)
    nav_link = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//nav//a[contains(@href,'category') or contains(translate(text(),'SHOP','shop'),'shop')]"))
    )
    nav_link.click()
    products = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb,.product-layout")))
    assert len(products) > 0, "No products found on catalog page"''',

    "SC-002": '''\
    driver.get("{url}index.php?route=product/category&path=20")
    wait = WebDriverWait(driver, 20)
    wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".product-thumb,.product-layout")))
    driver.execute_script("window.scrollTo(0, 400)")
    apple_filter = wait.until(
        EC.presence_of_element_located((By.XPATH,
            "//*[contains(normalize-space(text()),'Apple')]"
            "[ancestor::*[contains(@class,'mz-filter') or contains(@class,'sidebar') or contains(@id,'filter') or contains(@class,'list-group')]]"
        ))
    )
    driver.execute_script("arguments[0].scrollIntoView({{block:'center'}});", apple_filter)
    driver.execute_script("arguments[0].click();", apple_filter)
    products = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb,.product-layout")))
    assert len(products) > 0, "No products after applying Apple filter"''',

    "SC-003": '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 30)
    product_link = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".product-thumb h4 a,.product-thumb .caption a")))
    product_link.click()
    name  = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "h1,h2.product-title")))
    price = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".price,[class*='price']")))
    assert name.text.strip(),  "Product name is empty on detail page"
    assert price.text.strip(), "Product price is empty on detail page"''',

    "SC-004": '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 20)
    items = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb,.product-layout,.carousel-item img")))
    assert len(items) > 0, "No products or featured items visible without login"''',

    "SC-005": '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 20)
    search_box = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "input[name='search'],#search input[type='text']")))
    search_box.clear()
    search_box.send_keys("iPhone")
    search_box.submit()
    results = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb,.product-layout")))
    assert len(results) > 0, "No results found when searching for iPhone"''',
}

_FALLBACK_BODY = '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 20)
    wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))
    assert driver.title, "Page failed to load"'''


def _build_test_function(scenario: dict) -> str:
    sc_id   = scenario["id"]
    fn_name = FUNCTION_NAMES.get(sc_id, f"test_{sc_id.lower().replace('-','_')}")
    title   = scenario.get("title", sc_id).replace('"', "'")
    url     = scenario.get("kane_url", TARGET_URL)
    body    = SELENIUM_BODIES.get(sc_id, _FALLBACK_BODY).format(url=url)
    req_id  = scenario.get("requirement_id", "AC-000")
    return (
        f'@pytest.mark.scenario("{sc_id}")\n'
        f'@pytest.mark.requirement("{req_id}")\n'
        f'def {fn_name}(driver):\n'
        f'    """{sc_id}: {title}."""\n'
        f'{body}\n'
    )


# ── Stage 2: Sync scenarios (deterministic diff) ───────────────────────────
def sync_scenarios(requirements: list, existing: list) -> list:
    existing_by_req = {s["requirement_id"]: s for s in existing}
    current_req_ids = {r["id"] for r in requirements}

    max_num = 0
    for sc in existing:
        m = re.match(r"SC-(\d+)", sc.get("id", ""))
        if m:
            max_num = max(max_num, int(m.group(1)))
    next_num = max_num + 1

    result = []
    for req in requirements:
        existing_sc = existing_by_req.get(req["id"])
        if existing_sc is None:
            sc_id  = f"SC-{next_num:03d}"
            tc_id  = f"TC-{next_num:03d}"
            next_num += 1
            status = "new"
        else:
            sc_id  = existing_sc["id"]
            tc_id  = existing_sc.get("test_case_id", sc_id.replace("SC-", "TC-"))
            status = (
                "updated" if existing_sc.get("source_description") != req["description"]
                else "active"
            )

        result.append({
            "id":                 sc_id,
            "test_case_id":       tc_id,
            "requirement_id":     req["id"],
            "title":              req.get("kane_one_liner") or req.get("title", req["id"]),
            "status":             status,
            "source_description": req["description"],
            "steps":              req.get("kane_steps") or [
                f"Navigate to {TARGET_URL}", "Verify the acceptance criterion"
            ],
            "expected_result":    req.get("kane_summary") or req["description"],
            "kane_url":           TARGET_URL,
            "last_verified":      TODAY,
        })

    # Preserve deprecated entries for removed requirements
    for sc in existing:
        if sc["requirement_id"] not in current_req_ids:
            result.append({**sc, "status": "deprecated"})

    return result


# ── Stage 3: Generate tests ─────────────────────────────────────────────────
def generate_tests(scenarios: list) -> None:
    active = [s for s in scenarios if s["status"] != "deprecated"]
    lines  = [TEST_HEADER.rstrip(), ""]
    objectives = []
    for sc in active:
        lines.append(_build_test_function(sc).rstrip())
        lines.append("")
        objectives.append({
            "scenario_id": sc["id"],
            "test_case_id": sc.get("test_case_id", ""),
            "objective": sc.get("title", sc["id"]),
        })

    out = Path("tests/selenium/test_products.py")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    Path("kane").mkdir(exist_ok=True)
    Path("kane/objectives.json").write_text(json.dumps(objectives, indent=2), encoding="utf-8")
    print(f"[generate_tests] wrote {len(active)} test(s)")


# ── Stage 4: Write test selection ──────────────────────────────────────────
def write_test_selection(scenarios: list) -> list:
    if FULL_RUN:
        selected = [s for s in scenarios if s["status"] != "deprecated"]
    else:
        selected = [s for s in scenarios if s["status"] in ("new", "updated")]

    lines = []
    for sc in selected:
        fn = FUNCTION_NAMES.get(sc["id"], f"test_{sc['id'].lower().replace('-','_')}")
        lines.append(f"tests/selenium/test_products.py::{fn}")

    Path("reports").mkdir(exist_ok=True)
    Path("reports/pytest_selection.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    run_type = "full" if FULL_RUN else "incremental"
    manifest = {
        "selected_scenarios": [s["id"] for s in selected],
        "run_type": run_type,
    }
    Path("reports/test_execution_manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    print(f"[test_selection] {len(lines)} test(s) — {run_type} run")
    return selected


# ── Stage 5: Run HyperExecute ──────────────────────────────────────────────
def run_hyperexecute() -> str:
    cli = "./hyperexecute"
    if not Path(cli).exists():
        print("[hyperexecute] binary not found — skipping")
        return ""

    cmd = [cli, "--user", LT_USERNAME, "--key", LT_ACCESS_KEY, "--config", "hyperexecute.yaml"]
    print("[hyperexecute] starting ...")
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=1800)
    combined = result.stdout + result.stderr

    Path("reports").mkdir(exist_ok=True)
    Path("reports/hyperexecute-cli.log").write_text(combined, encoding="utf-8")

    match = JOB_ID_RE.search(combined)
    job_id = match.group(1) if match else ""
    print(f"[hyperexecute] done — job_id={job_id!r}  exit_code={result.returncode}")
    return job_id


# ── Stage 6: Fetch results ────────────────────────────────────────────────

# MCP responses wrap JSON in a markdown code block: ```json\n{...}\n```
_JSON_BLOCK_RE = re.compile(r"```json\s*([\s\S]*?)\s*```")


def _parse_mcp_text(text: str) -> object:
    """Parse JSON from an MCP response, stripping any markdown code fence."""
    m = _JSON_BLOCK_RE.search(text)
    candidate = m.group(1) if m else text.strip()
    return json.loads(candidate)


async def _fetch_he_sessions(job_id: str) -> list:
    """
    Fetch per-test session results from the HyperExecute sessions API using job_id.
    Uses cursor-based pagination to collect all sessions.
    Returns list of sessions in he_tasks format.
    """
    if not job_id:
        return []
    tasks = []
    cursor = None
    page = 0
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            while True:
                params: dict = {"limit": 20}
                if cursor:
                    params["cursor"] = cursor
                resp = await client.get(
                    f"https://api.hyperexecute.cloud/v2.0/job/{job_id}/sessions",
                    params=params,
                    auth=(LT_USERNAME, LT_ACCESS_KEY),
                )
                if resp.status_code != 200:
                    print(f"[he_sessions] API {resp.status_code} (page {page}) — {resp.text[:200]}")
                    break
                data = resp.json()
                page_sessions = data.get("data", [])
                print(f"[he_sessions] page {page}: {len(page_sessions)} session(s)")
                for s in page_sessions:
                    scenario_name = s.get("scenario_name") or s.get("name", "")
                    test_id   = s.get("testID", "")
                    task_id   = s.get("taskID", "")
                    status    = s.get("status", "unknown")
                    tasks.append({
                        "name":         scenario_name,
                        "task_id":      task_id,
                        "status":       status,
                        "session_link": (
                            f"https://automation.lambdatest.com/test?testID={test_id}"
                            if test_id else ""
                        ),
                    })
                metadata = data.get("metadata", {})
                if not metadata.get("hasmore"):
                    break
                cursor = metadata.get("cursor")
                if not cursor:
                    break
                page += 1
    except Exception as exc:
        print(f"[he_sessions] error: {exc}")
    print(f"[he_sessions] total {len(tasks)} session(s) for job {job_id}")
    return tasks


async def fetch_and_save_mcp_results(job_id: str) -> None:
    if not job_id:
        print("[mcp] no job_id — writing empty api_details.json")
        _write_api_details({}, [], job_id)
        return

    mcp_url_auth = f"{MCP_URL}?username={LT_USERNAME}&accessKey={LT_ACCESS_KEY}"
    headers = {"x-lt-username": LT_USERNAME, "x-lt-access-key": LT_ACCESS_KEY}

    try:
        async with sse_client(mcp_url_auth, headers=headers) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()

                # Poll until job is no longer running (max 15 min)
                # Response structure: { "jobInfo": { "status": "...", ... } }
                job_data: dict = {}
                job_inner: dict = {}
                for attempt in range(30):
                    raw = await session.call_tool("getHyperExecuteJobInfo", {"jobId": job_id})
                    text = raw.content[0].text if raw.content else "{}"
                    try:
                        job_data  = _parse_mcp_text(text)
                        job_inner = job_data.get("jobInfo") or job_data.get("data") or job_data
                    except (json.JSONDecodeError, AttributeError):
                        job_inner = {}
                    status = job_inner.get("status", "unknown")
                    print(f"[mcp] attempt {attempt+1} — job status: {status}")
                    if status not in ("running", "initiated", "queued"):
                        break
                    await asyncio.sleep(30)

                # Fetch per-test results from HyperExecute sessions API using job_id
                he_tasks = await _fetch_he_sessions(job_id)

                _write_api_details(job_inner, he_tasks, job_id)

    except Exception as exc:
        print(f"[mcp] connection failed: {exc} — falling back to HE sessions API")
        he_tasks = await _fetch_he_sessions(job_id)
        _write_api_details({}, he_tasks, job_id)


def _write_api_details(job_inner: dict, he_tasks: list, job_id: str) -> None:
    he_summary = {
        "job_id":                job_inner.get("jobId") or job_id,
        "job_link":              job_inner.get("jobLink") or (
            f"https://hyperexecute.lambdatest.com/hyperexecute/task?jobId={job_id}" if job_id else ""
        ),
        "status":                job_inner.get("status", "unknown"),
        "total_tasks":           job_inner.get("totalTasks", len(he_tasks)),
        "selenium_reports_link": job_inner.get("seleniumReportsLink", ""),
        "runtime_logs_link":     job_inner.get("runtimeLogsLink", ""),
    }
    api_details = {"he_summary": he_summary, "he_tasks": he_tasks, "kane_sessions": []}
    Path("reports").mkdir(exist_ok=True)
    Path("reports/api_details.json").write_text(
        json.dumps(api_details, indent=2), encoding="utf-8"
    )
    print(f"[api_details] saved {len(he_tasks)} test session(s) — job status={he_summary['status']}")


# ── Stage 7: Release recommendation (threshold-based) ─────────────────────
def _dedup_tasks(he_tasks: list) -> list:
    """Deduplicate by test name, keeping the first occurrence (LT API returns newest first)."""
    seen: dict = {}
    for t in he_tasks:
        key = t.get("name") or t.get("task_id", "")
        seen.setdefault(key, t)
    return list(seen.values())


def write_recommendation(he_tasks: list, requirements_total: int) -> None:
    he_tasks = _dedup_tasks(he_tasks)
    total  = len(he_tasks)
    passed = sum(1 for t in he_tasks if t["status"] == "passed")
    failed = total - passed
    pass_rate = round(passed / total * 100, 1) if total > 0 else 0.0

    if total == 0:
        verdict = "YELLOW"
        rec = "Test results not yet available — manual review required before release."
    elif pass_rate >= 80:
        verdict = "GREEN"
        rec = f"Approve release — {passed}/{total} tests passed ({pass_rate}%)."
    elif pass_rate >= 60:
        verdict = "YELLOW"
        rec = f"Conditional release — {failed} test(s) failed. Review failures before proceeding."
    else:
        verdict = "RED"
        rec = f"Block release — pass rate is {pass_rate}% ({failed} failed). Investigate failures."

    failing_lines = (
        "- None" if failed == 0
        else "\n".join(
            f"- {t['name'] or t['task_id']}"
            for t in he_tasks if t["status"] != "passed"
        )
    )

    content = f"""# QA Release Recommendation
**Verdict:** {verdict}
## Summary
- Requirements covered: {requirements_total}/{requirements_total}
- Scenarios executed: {total}
- Pass rate: {pass_rate}% ({passed} passed, {failed} failed)
## Failing Scenarios
{failing_lines}
## Recommendation
{rec}
"""
    Path("reports/release_recommendation.md").write_text(content, encoding="utf-8")
    print(f"[recommendation] Verdict: {verdict}  pass_rate={pass_rate}%")


# ── Post-pipeline: deterministic CI report scripts ─────────────────────────
def post_pipeline() -> None:
    for script in ["ci/build_traceability.py", "ci/write_github_summary.py"]:
        print(f"\n[post-pipeline] running {script} ...")
        result = subprocess.run(
            ["python", script],
            capture_output=True, text=True, encoding="utf-8",
        )
        if result.stdout:
            print(result.stdout)
        if result.returncode != 0:
            print(f"[WARNING] {script} exited {result.returncode}: {result.stderr[:500]}")
        else:
            print(f"[post-pipeline] {script} ok")


# ── Main ────────────────────────────────────────────────────────────────────
async def main() -> None:
    print(f"[pipeline] starting — FULL_RUN={FULL_RUN}  BUILD={BUILD_NAME}")

    # Stage 2: Sync scenarios
    req_path = Path("requirements/analyzed_requirements.json")
    requirements = json.loads(req_path.read_text(encoding="utf-8"))
    sc_path  = Path("scenarios/scenarios.json")
    existing = json.loads(sc_path.read_text(encoding="utf-8")) if sc_path.exists() else []
    scenarios = sync_scenarios(requirements, existing)
    sc_path.write_text(json.dumps(scenarios, indent=2), encoding="utf-8")
    counts = {s: sum(1 for x in scenarios if x["status"] == s) for s in ("new", "updated", "active", "deprecated")}
    print(f"[scenarios] {counts}")

    # Stage 3: Generate tests
    generate_tests(scenarios)

    # Stage 4: Write test selection
    write_test_selection(scenarios)

    # Stage 5: Run HyperExecute
    job_id = run_hyperexecute()

    # Stage 6: Fetch MCP results → reports/api_details.json
    await fetch_and_save_mcp_results(job_id)

    # Stage 7: Release recommendation
    api_details = json.loads(Path("reports/api_details.json").read_text(encoding="utf-8"))
    write_recommendation(api_details.get("he_tasks", []), len(requirements))

    # Post: CI report scripts (traceability + GitHub summary)
    post_pipeline()
    print("\n[pipeline] complete")


if __name__ == "__main__":
    asyncio.run(main())
