#!/usr/bin/env python3
"""
Agentic STLC Orchestrator — Stages 2-5.
Fully deterministic: no LLM required.
"""
import asyncio
import json
import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import httpx
from mcp import ClientSession
from mcp.client.sse import sse_client

# ── Runtime config ─────────────────────────────────────────────────────────
MCP_URL           = "https://mcp.lambdatest.com/mcp"
LT_API_BASE       = "https://api.lambdatest.com/automation/api/v1"
LT_USERNAME       = os.environ.get("LT_USERNAME", "")
LT_ACCESS_KEY     = os.environ.get("LT_ACCESS_KEY", "")
FULL_RUN          = os.environ.get("FULL_RUN", "true").lower() == "true"
TARGET_URL        = os.environ.get("POWERAPPS_URL", "https://apps.powerapps.com/play/")
TODAY             = datetime.now(timezone.utc).date().isoformat()
RUN_NUMBER        = os.environ.get("GITHUB_RUN_NUMBER", "")
BUILD_NAME        = (
    f"Agentic STLC #{RUN_NUMBER} | {TODAY}" if RUN_NUMBER
    else f"Agentic STLC | {TODAY}"
)

JOB_ID_RE = re.compile(r"jobId=([\w-]+)")

# ── Deterministic test generation ──────────────────────────────────────────
def _derive_fn_name(sc_id: str, title: str) -> str:
    """Derive a stable pytest function name from scenario ID + title."""
    slug = re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")[:50]
    return f"test_{sc_id.lower().replace('-', '_')}_{slug}"

TEST_HEADER = '''\
"""
Playwright test suite for Microsoft Teams Power Apps — generated by Agentic STLC pipeline. Do not edit manually.
"""
import pytest
from playwright.sync_api import expect

'''

PLAYWRIGHT_BODIES = {
    "SC-001": '''\
    from tests.playwright.conftest import _m365_login
    _m365_login(page, "{url}")
    page.wait_for_load_state("networkidle", timeout=30000)
    # Power Apps canvas loads; wait for at least one issue card or list item
    issue_items = page.locator("[aria-label*='Issue'], [aria-label*='Report'], [role='listitem'], [data-control-name]")
    issue_items.first.wait_for(timeout=20000)
    assert issue_items.count() > 0, "No issue items visible in the main list"''',

    "SC-002": '''\
    from tests.playwright.conftest import _m365_login
    _m365_login(page, "{url}")
    page.wait_for_load_state("networkidle", timeout=30000)
    # Click the New Issue / Report Issue button
    new_btn = page.get_by_role("button", name=["New", "Report Issue", "New Issue", "+ New"]).first
    new_btn.wait_for(timeout=15000)
    new_btn.click()
    page.wait_for_load_state("networkidle", timeout=10000)
    # Fill in the issue title field
    title_field = page.get_by_role("textbox").first
    title_field.wait_for(timeout=10000)
    title_field.fill("Agentic STLC Test Issue")
    # Submit the form
    submit_btn = page.get_by_role("button", name=["Submit", "Save", "Create"]).first
    submit_btn.click()
    page.wait_for_load_state("networkidle", timeout=10000)
    assert page.locator("[aria-label*='Issue'], [role='listitem']").count() > 0, "Issue list not visible after submit"''',

    "SC-003": '''\
    from tests.playwright.conftest import _m365_login
    _m365_login(page, "{url}")
    page.wait_for_load_state("networkidle", timeout=30000)
    # Open the first issue in the list
    first_item = page.locator("[role='listitem'], [aria-label*='Issue']").first
    first_item.wait_for(timeout=15000)
    first_item.click()
    page.wait_for_load_state("networkidle", timeout=10000)
    # Expect detail view: title, status, and description visible
    detail_content = page.locator("[role='main'], [data-control-name*='detail'], [aria-label*='Status'], [aria-label*='Description']")
    detail_content.first.wait_for(timeout=10000)
    assert detail_content.count() > 0, "Issue detail view did not load"''',

    "SC-004": '''\
    from tests.playwright.conftest import _m365_login
    _m365_login(page, "{url}")
    page.wait_for_load_state("networkidle", timeout=30000)
    # Find and click the Status filter dropdown
    status_filter = page.get_by_role("combobox").or_(page.get_by_role("listbox")).or_(
        page.get_by_label("Status")
    ).first
    status_filter.wait_for(timeout=15000)
    status_filter.click()
    # Select "Active" option
    active_option = page.get_by_role("option", name="Active").or_(page.get_by_text("Active")).first
    active_option.wait_for(timeout=5000)
    active_option.click()
    page.wait_for_load_state("networkidle", timeout=10000)
    # Verify filtered results are shown
    filtered_items = page.locator("[role='listitem'], [aria-label*='Issue']")
    assert filtered_items.count() >= 0, "Filter applied — list updated"''',

    "SC-005": '''\
    from tests.playwright.conftest import _m365_login
    _m365_login(page, "{url}")
    page.wait_for_load_state("networkidle", timeout=30000)
    # Open an issue detail
    first_item = page.locator("[role='listitem'], [aria-label*='Issue']").first
    first_item.wait_for(timeout=15000)
    first_item.click()
    page.wait_for_load_state("networkidle", timeout=10000)
    # Navigate back via back button or breadcrumb
    back_btn = page.get_by_role("button", name=["Back", "Cancel", "Close"]).first
    if back_btn.count() == 0:
        page.go_back()
    else:
        back_btn.click()
    page.wait_for_load_state("networkidle", timeout=10000)
    # Verify main list is visible again
    issue_items = page.locator("[role='listitem'], [aria-label*='Issue']")
    issue_items.first.wait_for(timeout=10000)
    assert issue_items.count() > 0, "Issues list not restored after navigating back"''',
}

_FALLBACK_BODY = '''\
    from tests.playwright.conftest import _m365_login
    _m365_login(page, "{url}")
    page.wait_for_load_state("networkidle", timeout=30000)
    assert page.title(), "Page failed to load"'''


def _build_test_function(scenario: dict) -> str:
    sc_id   = scenario["id"]
    fn_name = scenario.get("function_name") or _derive_fn_name(sc_id, scenario.get("title", sc_id))
    title   = scenario.get("title", sc_id).replace('"', "'")
    url     = scenario.get("kane_url", TARGET_URL)
    body    = PLAYWRIGHT_BODIES.get(sc_id, _FALLBACK_BODY).format(url=url)
    req_id  = scenario.get("requirement_id", "AC-000")
    return (
        f'@pytest.mark.scenario("{sc_id}")\n'
        f'@pytest.mark.requirement("{req_id}")\n'
        f'def {fn_name}(page):\n'
        f'    """{sc_id}: {title}."""\n'
        f'{body}\n'
    )


# ── Stage 2: Sync scenarios (deterministic diff) ───────────────────────────
def sync_scenarios(requirements: list, existing: list) -> list:
    existing_by_req = {s["requirement_id"]: s for s in existing}
    current_req_ids = {r["id"] for r in requirements}

    max_num = 0
    for sc in existing:
        m = re.match(r"SC-(\d+)", sc.get("id", ""))
        if m:
            max_num = max(max_num, int(m.group(1)))
    next_num = max_num + 1

    result = []
    for req in requirements:
        existing_sc = existing_by_req.get(req["id"])
        if existing_sc is None:
            sc_id  = f"SC-{next_num:03d}"
            tc_id  = f"TC-{next_num:03d}"
            next_num += 1
            status = "new"
        else:
            sc_id  = existing_sc["id"]
            tc_id  = existing_sc.get("test_case_id", sc_id.replace("SC-", "TC-"))
            status = (
                "updated" if existing_sc.get("source_description") != req["description"]
                else "active"
            )

        title = req.get("kane_one_liner") or req.get("title", req["id"])
        fn_name = (
            existing_sc.get("function_name")
            if existing_sc
            else _derive_fn_name(sc_id, title)
        )
        result.append({
            "id":                 sc_id,
            "test_case_id":       tc_id,
            "requirement_id":     req["id"],
            "title":              title,
            "function_name":      fn_name,
            "status":             status,
            "source_description": req["description"],
            "steps":              req.get("kane_steps") or [
                f"Navigate to {TARGET_URL}", "Verify the acceptance criterion"
            ],
            "expected_result":    req.get("kane_summary") or req["description"],
            "kane_url":           TARGET_URL,
            "last_verified":      TODAY,
        })

    # Preserve deprecated entries for removed requirements
    for sc in existing:
        if sc["requirement_id"] not in current_req_ids:
            deprecated = {**sc, "status": "deprecated"}
            if "function_name" not in deprecated:
                deprecated["function_name"] = _derive_fn_name(sc["id"], sc.get("title", sc["id"]))
            result.append(deprecated)

    return result


# ── Stage 3: Generate tests ─────────────────────────────────────────────────
def generate_tests(scenarios: list) -> None:
    active = [s for s in scenarios if s["status"] != "deprecated"]
    lines  = [TEST_HEADER.rstrip(), ""]
    objectives = []
    for sc in active:
        lines.append(_build_test_function(sc).rstrip())
        lines.append("")
        objectives.append({
            "scenario_id": sc["id"],
            "test_case_id": sc.get("test_case_id", ""),
            "objective": sc.get("title", sc["id"]),
        })

    out = Path("tests/playwright/test_powerapps.py")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    # Ensure function_name is set on each active scenario (for downstream scripts)
    for sc in active:
        if not sc.get("function_name"):
            sc["function_name"] = _derive_fn_name(sc["id"], sc.get("title", sc["id"]))

    Path("kane").mkdir(exist_ok=True)
    Path("kane/objectives.json").write_text(json.dumps(objectives, indent=2), encoding="utf-8")
    print(f"[generate_tests] wrote {len(active)} test(s)")


# ── Stage 4: Write test selection ──────────────────────────────────────────
def write_test_selection(scenarios: list) -> list:
    if FULL_RUN:
        selected = [s for s in scenarios if s["status"] != "deprecated"]
    else:
        selected = [s for s in scenarios if s["status"] in ("new", "updated")]

    lines = []
    for sc in selected:
        fn = sc.get("function_name") or _derive_fn_name(sc["id"], sc.get("title", sc["id"]))
        lines.append(f"tests/playwright/test_powerapps.py::{fn}")

    Path("reports").mkdir(exist_ok=True)
    Path("reports/pytest_selection.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    run_type = "full" if FULL_RUN else "incremental"
    manifest = {
        "selected_scenarios": [s["id"] for s in selected],
        "run_type": run_type,
    }
    Path("reports/test_execution_manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    print(f"[test_selection] {len(lines)} test(s) — {run_type} run")
    return selected


# ── Stage 5: Run HyperExecute ──────────────────────────────────────────────
def run_hyperexecute() -> str:
    cli = "./hyperexecute"
    if not Path(cli).exists():
        print("[hyperexecute] binary not found — skipping")
        return ""

    cmd = [cli, "--user", LT_USERNAME, "--key", LT_ACCESS_KEY, "--config", "hyperexecute.yaml"]
    print("[hyperexecute] starting ...")
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=1800)
    combined = result.stdout + result.stderr

    Path("reports").mkdir(exist_ok=True)
    Path("reports/hyperexecute-cli.log").write_text(combined, encoding="utf-8")

    match = JOB_ID_RE.search(combined)
    job_id = match.group(1) if match else ""
    print(f"[hyperexecute] done — job_id={job_id!r}  exit_code={result.returncode}")
    return job_id


# ── Stage 6: Fetch results ────────────────────────────────────────────────

# MCP responses wrap JSON in a markdown code block: ```json\n{...}\n```
_JSON_BLOCK_RE = re.compile(r"```json\s*([\s\S]*?)\s*```")


def _parse_mcp_text(text: str) -> object:
    """Parse JSON from an MCP response, stripping any markdown code fence."""
    m = _JSON_BLOCK_RE.search(text)
    candidate = m.group(1) if m else text.strip()
    return json.loads(candidate)


def _parse_session(s: dict, source: str) -> dict:
    """Normalise a session record from either the HE API or the Automation API."""
    raw_name = (
        s.get("scenario_name") or s.get("name") or s.get("session_name", "")
    )
    # conftest names sessions "SC-001 | TC-001 | test_sc_001_..." — extract fn name
    parts   = [p.strip() for p in raw_name.split("|")]
    fn_name = parts[-1] if len(parts) > 1 else raw_name
    test_id = s.get("testID") or s.get("test_id") or s.get("session_id", "")
    task_id = s.get("taskID") or s.get("task_id", "")
    status_raw = s.get("status") or s.get("status_ind", "unknown")
    status = "passed" if status_raw in ("passed", "pass", "completed") else (
        "failed" if status_raw in ("failed", "fail", "error") else status_raw
    )
    link = (
        f"https://automation.lambdatest.com/test?testID={test_id}"
        if test_id else ""
    )
    print(f"  [{source}] {fn_name!r} → {status}  testID={test_id}")
    return {"name": fn_name, "task_id": task_id, "status": status, "session_link": link}


async def _fetch_he_sessions_api(client: httpx.AsyncClient, job_id: str) -> list:
    """Try HyperExecute /v2.0/job/{id}/sessions endpoint."""
    tasks = []
    cursor = None
    page = 0
    while True:
        params: dict = {"limit": 20}
        if cursor:
            params["cursor"] = cursor
        resp = await client.get(
            f"https://api.hyperexecute.cloud/v2.0/job/{job_id}/sessions",
            params=params,
            auth=(LT_USERNAME, LT_ACCESS_KEY),
        )
        if resp.status_code != 200:
            print(f"[he_sessions_api] {resp.status_code} — {resp.text[:200]}")
            return []
        data = resp.json()
        page_sessions = data.get("data", [])
        print(f"[he_sessions_api] page {page}: {len(page_sessions)} session(s)")
        tasks.extend(_parse_session(s, "he_api") for s in page_sessions)
        metadata = data.get("metadata", {})
        if not metadata.get("hasmore"):
            break
        cursor = metadata.get("cursor")
        if not cursor:
            break
        page += 1
    return tasks


async def _fetch_automation_sessions_by_build(client: httpx.AsyncClient, build_name: str) -> list:
    """
    Fall back to LambdaTest Automation API: find the build by name and return its sessions.
    conftest.py sets build=BUILD_NAME, so the build should be searchable by that exact name.
    """
    # Search for the build; also try a broad "Agentic STLC" search if exact match fails
    build_id = None
    for search in (build_name, "Agentic STLC"):
        resp = await client.get(
            f"{LT_API_BASE}/builds",
            params={"s": search, "limit": 5, "sort": "desc"},
            auth=(LT_USERNAME, LT_ACCESS_KEY),
        )
        if resp.status_code != 200:
            print(f"[automation] builds search {resp.status_code}")
            continue
        builds = resp.json().get("data", [])
        print(f"[automation] {len(builds)} build(s) for search={search!r}")
        # Pick first build whose name contains the expected run number/date
        for b in builds:
            name = b.get("name", "")
            if build_name in name or search == "Agentic STLC":
                build_id = b.get("build_id")
                print(f"[automation] matched build_id={build_id!r} name={name!r}")
                break
        if build_id:
            break

    if not build_id:
        print("[automation] no matching build found")
        return []

    resp = await client.get(
        f"{LT_API_BASE}/sessions",
        params={"build_id": build_id, "limit": 50},
        auth=(LT_USERNAME, LT_ACCESS_KEY),
    )
    if resp.status_code != 200:
        print(f"[automation] sessions {resp.status_code}")
        return []
    sessions = resp.json().get("data", [])
    print(f"[automation] {len(sessions)} session(s) for build_id={build_id}")
    return [_parse_session(s, "automation") for s in sessions]


async def _fetch_he_sessions(job_id: str) -> list:
    """
    Fetch per-test session results.
    Strategy 1: HyperExecute /v2.0/job/{id}/sessions  (direct, by job_id)
    Strategy 2: LambdaTest Automation API /builds + /sessions (by build name)
    """
    async with httpx.AsyncClient(timeout=30) as client:
        tasks = []
        if job_id:
            try:
                tasks = await _fetch_he_sessions_api(client, job_id)
            except Exception as exc:
                print(f"[he_sessions_api] error: {exc}")

        if not tasks:
            print(f"[he_sessions] HE API returned 0 — trying Automation API (build={BUILD_NAME!r})")
            try:
                tasks = await _fetch_automation_sessions_by_build(client, BUILD_NAME)
            except Exception as exc:
                print(f"[automation] error: {exc}")

    print(f"[he_sessions] final: {len(tasks)} session(s)")
    return tasks


async def fetch_and_save_mcp_results(job_id: str) -> None:
    if not job_id:
        print("[mcp] no job_id — writing empty api_details.json")
        _write_api_details({}, [], job_id)
        return

    mcp_url_auth = f"{MCP_URL}?username={LT_USERNAME}&accessKey={LT_ACCESS_KEY}"
    headers = {"x-lt-username": LT_USERNAME, "x-lt-access-key": LT_ACCESS_KEY}

    try:
        async with sse_client(mcp_url_auth, headers=headers) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()

                # Poll until job is no longer running (max 15 min)
                # Response structure: { "jobInfo": { "status": "...", ... } }
                job_data: dict = {}
                job_inner: dict = {}
                for attempt in range(30):
                    raw = await session.call_tool("getHyperExecuteJobInfo", {"jobId": job_id})
                    text = raw.content[0].text if raw.content else "{}"
                    try:
                        job_data  = _parse_mcp_text(text)
                        job_inner = job_data.get("jobInfo") or job_data.get("data") or job_data
                    except (json.JSONDecodeError, AttributeError):
                        job_inner = {}
                    status = job_inner.get("status", "unknown")
                    print(f"[mcp] attempt {attempt+1} — job status: {status}")
                    if status not in ("running", "initiated", "queued"):
                        break
                    await asyncio.sleep(30)

                # Fetch per-test results from HyperExecute sessions API using job_id
                he_tasks = await _fetch_he_sessions(job_id)

                _write_api_details(job_inner, he_tasks, job_id)

    except Exception as exc:
        print(f"[mcp] connection failed: {exc} — falling back to HE sessions API")
        he_tasks = await _fetch_he_sessions(job_id)
        _write_api_details({}, he_tasks, job_id)


def _write_api_details(job_inner: dict, he_tasks: list, job_id: str) -> None:
    he_summary = {
        "job_id":                job_inner.get("jobId") or job_id,
        "job_link":              job_inner.get("jobLink") or (
            f"https://hyperexecute.lambdatest.com/hyperexecute/task?jobId={job_id}" if job_id else ""
        ),
        "status":                job_inner.get("status", "unknown"),
        "total_tasks":           job_inner.get("totalTasks", len(he_tasks)),
        "selenium_reports_link": job_inner.get("seleniumReportsLink", ""),
        "runtime_logs_link":     job_inner.get("runtimeLogsLink", ""),
    }
    api_details = {"he_summary": he_summary, "he_tasks": he_tasks, "kane_sessions": []}
    Path("reports").mkdir(exist_ok=True)
    Path("reports/api_details.json").write_text(
        json.dumps(api_details, indent=2), encoding="utf-8"
    )
    print(f"[api_details] saved {len(he_tasks)} test session(s) — job status={he_summary['status']}")


# ── Stage 7: Release recommendation (threshold-based) ─────────────────────
def _dedup_tasks(he_tasks: list) -> list:
    """Deduplicate by test name, keeping the first occurrence (LT API returns newest first)."""
    seen: dict = {}
    for t in he_tasks:
        key = t.get("name") or t.get("task_id", "")
        seen.setdefault(key, t)
    return list(seen.values())


def write_recommendation(he_tasks: list, requirements_total: int) -> None:
    he_tasks = _dedup_tasks(he_tasks)
    total  = len(he_tasks)
    passed = sum(1 for t in he_tasks if t["status"] == "passed")
    failed = total - passed
    pass_rate = round(passed / total * 100, 1) if total > 0 else 0.0

    if total == 0:
        verdict = "YELLOW"
        rec = "Test results not yet available — manual review required before release."
    elif pass_rate >= 80:
        verdict = "GREEN"
        rec = f"Approve release — {passed}/{total} tests passed ({pass_rate}%)."
    elif pass_rate >= 60:
        verdict = "YELLOW"
        rec = f"Conditional release — {failed} test(s) failed. Review failures before proceeding."
    else:
        verdict = "RED"
        rec = f"Block release — pass rate is {pass_rate}% ({failed} failed). Investigate failures."

    failing_lines = (
        "- None" if failed == 0
        else "\n".join(
            f"- {t['name'] or t['task_id']}"
            for t in he_tasks if t["status"] != "passed"
        )
    )

    content = f"""# QA Release Recommendation
**Verdict:** {verdict}
## Summary
- Requirements covered: {requirements_total}/{requirements_total}
- Scenarios executed: {total}
- Pass rate: {pass_rate}% ({passed} passed, {failed} failed)
## Failing Scenarios
{failing_lines}
## Recommendation
{rec}
"""
    Path("reports/release_recommendation.md").write_text(content, encoding="utf-8")
    print(f"[recommendation] Verdict: {verdict}  pass_rate={pass_rate}%")


# ── Post-pipeline: deterministic CI report scripts ─────────────────────────
def post_pipeline() -> None:
    # Order matters: normalize → validate → traceability → release → summary
    scripts = [
        "ci/normalize_artifacts.py",
        "ci/validate_report.py",
        "ci/build_traceability.py",
        "ci/release_recommendation.py",
        "ci/write_github_summary.py",
    ]
    for script in scripts:
        print(f"\n[post-pipeline] running {script} ...")
        result = subprocess.run(
            ["python", script],
            capture_output=True, text=True, encoding="utf-8",
        )
        if result.stdout:
            print(result.stdout)
        if result.returncode != 0:
            print(f"[WARNING] {script} exited {result.returncode}: {result.stderr[:500]}")
        else:
            print(f"[post-pipeline] {script} ok")


# ── Main ────────────────────────────────────────────────────────────────────
async def main() -> None:
    print(f"[pipeline] starting — FULL_RUN={FULL_RUN}  BUILD={BUILD_NAME}")

    # Stage 2: Sync scenarios
    req_path = Path("requirements/analyzed_requirements.json")
    requirements = json.loads(req_path.read_text(encoding="utf-8"))
    sc_path  = Path("scenarios/scenarios.json")
    existing = json.loads(sc_path.read_text(encoding="utf-8")) if sc_path.exists() else []
    scenarios = sync_scenarios(requirements, existing)
    sc_path.write_text(json.dumps(scenarios, indent=2), encoding="utf-8")
    counts = {s: sum(1 for x in scenarios if x["status"] == s) for s in ("new", "updated", "active", "deprecated")}
    print(f"[scenarios] {counts}")

    # Stage 3: Generate tests (also stamps function_name onto each scenario)
    generate_tests(scenarios)

    # Persist scenarios.json with function_name now set
    sc_path.write_text(json.dumps(scenarios, indent=2), encoding="utf-8")

    # Stage 4: Write test selection
    write_test_selection(scenarios)

    # Stage 5: Run HyperExecute
    job_id = run_hyperexecute()

    # Stage 6: Fetch MCP results → reports/api_details.json
    await fetch_and_save_mcp_results(job_id)

    # Stage 7: Normalize artifacts → validate → traceability → release → summary
    post_pipeline()
    print("\n[pipeline] complete")


if __name__ == "__main__":
    asyncio.run(main())
