import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


FUNCTION_NAMES = {
    "SC-001": "test_sc_001_navigate_to_credit_cards_and_view_list",
    "SC-002": "test_sc_002_filter_cards_by_category",
    "SC-003": "test_sc_003_click_card_view_details",
    "SC-004": "test_sc_004_card_highlights_visible_without_login",
    "SC-005": "test_sc_005_relevant_results_for_selected_filter",
}


HEADER = '''"""
Selenium test suite for LambdaTest eCommerce playground browsing and search.
Generated by pure CI pipeline. Do not edit manually.
Each test maps to one acceptance criterion in requirements/search.txt.
"""

import pytest
from selenium.webdriver.support.ui import WebDriverWait
from tests.selenium.pages.credit_cards_page import CreditCardsPage

'''


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--scenarios", default="scenarios/scenarios.json")
    parser.add_argument("--tests-out", default="tests/selenium/test_credit_cards.py")
    parser.add_argument("--objectives-out", default="kane/objectives.json")
    return parser.parse_args()


def load_scenarios(path):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return [scenario for scenario in data if scenario.get("status") != "deprecated"]


def build_test_function(scenario):
    function_name = FUNCTION_NAMES.get(
        scenario["id"],
        f"test_{scenario['id'].lower().replace('-', '_')}",
    )
    title = scenario["title"].replace('"', "'")
    if scenario["id"] == "SC-001":
        body = '''
    page = CreditCardsPage(driver)
    page.navigate_to_credit_cards()

    assert "credit-card" in page.current_url().lower() or "credit-cards" in page.current_url().lower(), (
        f"Expected credit cards URL, got: {page.current_url()}"
    )

    card_tiles = page.get_card_tiles()
    assert len(card_tiles) > 0, "Expected at least one credit card tile to be visible on the page"
'''
    elif scenario["id"] == "SC-002":
        body = '''
    page = CreditCardsPage(driver)
    page.navigate_to_credit_cards()

    filter_chips = page.get_filter_chips()
    assert len(filter_chips) > 0, "Expected filter chips to be present on the credit cards page"

    filter_names = ["Travel", "Cash Back", "Rewards", "Featured", "Business"]
    applied = False
    for name in filter_names:
        if page.apply_filter(name):
            applied = True
            break

    assert applied, f"Could not apply any of the expected filters: {filter_names}"

    card_tiles = page.get_card_tiles()
    assert len(card_tiles) > 0, "Expected filtered card results to be displayed after applying a filter"
'''
    elif scenario["id"] == "SC-003":
        body = '''
    page = CreditCardsPage(driver)
    page.navigate_to_credit_cards()

    initial_url = page.current_url()
    clicked = page.click_first_card_details()
    assert clicked, "Could not find any View Details link or card tile to click"

    WebDriverWait(driver, 15).until(
        lambda current_driver: current_driver.current_url != initial_url or len(page.get_card_benefits_elements()) > 0
    )

    benefits = page.get_card_benefits_elements()
    assert len(benefits) > 0, (
        "Expected benefits, rewards, or annual fee information on the card detail page. "
        f"Current URL: {page.current_url()}"
    )
'''
    elif scenario["id"] == "SC-004":
        body = '''
    page = CreditCardsPage(driver)
    page.navigate_to_credit_cards()

    assert not page.is_login_gate_present(), "Expected the credit cards page to be browseable without an auth gate"
    assert page.has_guest_browsing_content(), "Expected card highlights or card tiles to be visible without logging in"
'''
    else:
        body = '''
    page = CreditCardsPage(driver)
    page.navigate_to_credit_cards()

    applied = page.apply_filter("Travel")
    if not applied:
        applied = page.apply_filter("Cash Back")

    assert applied, "Could not apply Travel or Cash Back filter"

    card_tiles = page.get_card_tiles()
    assert len(card_tiles) > 0, "Expected card results after applying a filter"

    page_text = driver.find_element("tag name", "body").text.lower()
    relevant_keywords = ["travel", "cash back", "reward", "points", "miles", "platinum", "gold"]
    assert any(keyword in page_text for keyword in relevant_keywords), (
        "Expected filtered results to contain relevant keywords matching the selected filter. "
        f"Checked for: {relevant_keywords}"
    )
'''

    return f'''@pytest.mark.scenario("{scenario["id"]}")
@pytest.mark.requirement("{scenario["requirement_id"]}")
def {function_name}(driver):
    """{scenario["id"]}: {title}."""
{body}
'''


def build_objectives(scenarios):
    today = datetime.now(timezone.utc).date().isoformat()
    objectives = []
    for scenario in scenarios:
        max_steps = 20 if scenario["id"] == "SC-003" else 15
        objectives.append(
            {
                "scenario_id": scenario["id"],
                "test_case_id": scenario["test_case_id"],
                "requirement_id": scenario["requirement_id"],
                "objective": scenario["kane_objective"],
                "url": scenario["kane_url"],
                "timeout": 180 if scenario["id"] == "SC-003" else 120,
                "max_steps": max_steps,
                "last_run_status": scenario.get("kane_last_status", "not_run"),
                "last_run_date": today if scenario.get("kane_last_status") else None,
            }
        )
    return objectives


def main():
    args = parse_args()
    scenarios = load_scenarios(args.scenarios)

    rendered = [HEADER.rstrip(), ""]
    for scenario in scenarios:
        rendered.append(build_test_function(scenario).rstrip())
        rendered.append("")

    test_output = Path(args.tests_out)
    test_output.parent.mkdir(parents=True, exist_ok=True)
    test_output.write_text("\n".join(rendered).rstrip() + "\n", encoding="utf-8")

    objectives = build_objectives(scenarios)
    objectives_path = Path(args.objectives_out)
    objectives_path.parent.mkdir(parents=True, exist_ok=True)
    objectives_path.write_text(json.dumps(objectives, indent=2) + "\n", encoding="utf-8")

    print(f"tests_generated={len(scenarios)} objectives_updated={len(objectives)}")


if __name__ == "__main__":
    main()
