import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


FUNCTION_NAMES = {
    "SC-001": "test_sc_001_navigate_to_products_and_view_list",
    "SC-002": "test_sc_002_filter_products_by_category",
    "SC-003": "test_sc_003_click_product_view_details",
    "SC-004": "test_sc_004_product_highlights_visible_without_login",
    "SC-005": "test_sc_005_relevant_results_for_selected_filter",
}


HEADER = '''"""
Selenium test suite for LambdaTest eCommerce playground.
Generated by CI pipeline. Do not edit manually.
"""

import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

'''

SELENIUM_BODIES = {
    "SC-001": '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 20)
    nav_link = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//nav//a[contains(@href, 'category') or contains(translate(text(),'SHOP','shop'),'shop')]"))
    )
    nav_link.click()
    products = wait.until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb, .product-layout"))
    )
    assert len(products) > 0, "No products found on catalog page"''',

    "SC-002": '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 20)
    apple_filter = wait.until(
        EC.element_to_be_clickable((By.XPATH, "//label[contains(., 'Apple')] | //a[contains(., 'Apple') and ancestor::*[contains(@class,'sidebar') or contains(@class,'filter') or contains(@class,'mz-filter')]]"))
    )
    apple_filter.click()
    products = wait.until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb, .product-layout"))
    )
    assert len(products) > 0, "No products after applying Apple filter"''',

    "SC-003": '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 30)
    product_link = wait.until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, ".product-thumb h4 a, .product-thumb .caption a"))
    )
    product_link.click()
    name = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "h1, h2.product-title")))
    price = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".price, [class*='price']")))
    assert name.text.strip(), "Product name is empty on detail page"
    assert price.text.strip(), "Product price is empty on detail page"''',

    "SC-004": '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 20)
    items = wait.until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb, .product-layout, .carousel-item img"))
    )
    assert len(items) > 0, "No products or featured items visible on homepage without login"''',

    "SC-005": '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 20)
    search_box = wait.until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, "input[name='search'], #search input[type='text']"))
    )
    search_box.clear()
    search_box.send_keys("iPhone")
    search_box.submit()
    results = wait.until(
        EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".product-thumb, .product-layout"))
    )
    assert len(results) > 0, "No results found when searching for iPhone"''',
}


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--scenarios", default="scenarios/scenarios.json")
    parser.add_argument("--tests-out", default="tests/selenium/test_products.py")
    parser.add_argument("--objectives-out", default="kane/objectives.json")
    return parser.parse_args()


def load_scenarios(path):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return [s for s in data if s.get("status") != "deprecated"]


_FALLBACK_BODY = '''\
    driver.get("{url}")
    wait = WebDriverWait(driver, 20)
    wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))
    assert driver.title, "Page failed to load"'''


def build_test_function(scenario):
    function_name = FUNCTION_NAMES.get(
        scenario["id"],
        f"test_{scenario['id'].lower().replace('-', '_')}",
    )
    title = scenario["title"].replace('"', "'")
    url = scenario["kane_url"]
    body = SELENIUM_BODIES.get(scenario["id"], _FALLBACK_BODY)
    body = body.format(url=url)

    return (
        f'@pytest.mark.scenario("{scenario["id"]}")\n'
        f'@pytest.mark.requirement("{scenario["requirement_id"]}")\n'
        f'def {function_name}(driver):\n'
        f'    """{scenario["id"]}: {title}."""\n'
        f'{body}\n'
    )


def build_objectives(scenarios):
    today = datetime.now(timezone.utc).date().isoformat()
    objectives = []
    for scenario in scenarios:
        objectives.append(
            {
                "scenario_id": scenario["id"],
                "test_case_id": scenario["test_case_id"],
                "requirement_id": scenario["requirement_id"],
                "objective": scenario["kane_objective"],
                "url": scenario["kane_url"],
                "timeout": 180 if scenario["id"] == "SC-003" else 120,
                "max_steps": 20 if scenario["id"] == "SC-003" else 15,
                "last_run_status": scenario.get("kane_last_status", "not_run"),
                "last_run_date": today if scenario.get("kane_last_status") else None,
            }
        )
    return objectives


def main():
    args = parse_args()
    scenarios = load_scenarios(args.scenarios)

    rendered = [HEADER.rstrip(), ""]
    for scenario in scenarios:
        rendered.append(build_test_function(scenario).rstrip())
        rendered.append("")

    test_output = Path(args.tests_out)
    test_output.parent.mkdir(parents=True, exist_ok=True)
    test_output.write_text("\n".join(rendered).rstrip() + "\n", encoding="utf-8")

    objectives = build_objectives(scenarios)
    objectives_path = Path(args.objectives_out)
    objectives_path.parent.mkdir(parents=True, exist_ok=True)
    objectives_path.write_text(json.dumps(objectives, indent=2) + "\n", encoding="utf-8")

    print(f"tests_generated={len(scenarios)} objectives_updated={len(objectives)}")


if __name__ == "__main__":
    main()
