import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


FUNCTION_NAMES = {
    "SC-001": "test_sc_001_navigate_to_products_and_view_list",
    "SC-002": "test_sc_002_filter_products_by_category",
    "SC-003": "test_sc_003_click_product_view_details",
    "SC-004": "test_sc_004_product_highlights_visible_without_login",
    "SC-005": "test_sc_005_relevant_results_for_selected_filter",
}


HEADER = '''"""
Selenium test suite for LambdaTest eCommerce playground browsing and search.
Generated by pure CI pipeline. Do not edit manually.
Each test maps to one acceptance criterion in requirements/search.txt.
"""

import pytest
from selenium.webdriver.support.ui import WebDriverWait
from tests.selenium.pages.products_page import ProductsPage

'''


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--scenarios", default="scenarios/scenarios.json")
    parser.add_argument("--tests-out", default="tests/selenium/test_products.py")
    parser.add_argument("--objectives-out", default="kane/objectives.json")
    return parser.parse_args()


def load_scenarios(path):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return [scenario for scenario in data if scenario.get("status") != "deprecated"]


def build_test_function(scenario):
    function_name = FUNCTION_NAMES.get(
        scenario["id"],
        f"test_{scenario['id'].lower().replace('-', '_')}",
    )
    title = scenario["title"].replace('"', "'")
    
    # Deterministic templates for Selenium tests
    if scenario["id"] == "SC-001":
        body = '''    page = ProductsPage(driver)
    page.navigate_to_products_page()

    assert "product" in page.current_url().lower() or "shop" in page.current_url().lower()
    product_tiles = page.get_product_tiles()
    assert len(product_tiles) > 0'''
    elif scenario["id"] == "SC-002":
        body = '''    page = ProductsPage(driver)
    page.navigate_to_products_page()

    filter_names = ["Apple", "Samsung", "HTC", "Canon", "Nikon", "Phones", "Laptops"]
    applied = False
    for name in filter_names:
        if page.apply_filter(name):
            applied = True
            break
    assert applied
    assert len(page.get_product_tiles()) > 0'''
    elif scenario["id"] == "SC-003":
        body = '''    page = ProductsPage(driver)
    page.navigate_to_products_page()

    initial_url = page.current_url()
    assert page.click_first_product_details()
    
    WebDriverWait(driver, 15).until(
        lambda d: d.current_url != initial_url or len(page.get_product_details_elements()) > 0
    )
    assert len(page.get_product_details_elements()) > 0'''
    elif scenario["id"] == "SC-004":
        body = '''    page = ProductsPage(driver)
    page.navigate_to_products_page()

    assert not page.is_login_gate_present()
    assert page.has_guest_browsing_content()'''
    else:
        body = f'''    # Scenario {scenario["id"]} handled by Kane AI Scripting Agent
    page = ProductsPage(driver)
    page.navigate_to_products_page()
    # Objective: {scenario["kane_objective"]}'''

    return f'''@pytest.mark.scenario("{scenario["id"]}")
@pytest.mark.requirement("{scenario["requirement_id"]}")
def {function_name}(driver):
    """{scenario["id"]}: {title}."""
{body}
'''


def build_objectives(scenarios):
    today = datetime.now(timezone.utc).date().isoformat()
    objectives = []
    for scenario in scenarios:
        max_steps = 20 if scenario["id"] == "SC-003" else 15
        objectives.append(
            {
                "scenario_id": scenario["id"],
                "test_case_id": scenario["test_case_id"],
                "requirement_id": scenario["requirement_id"],
                "objective": scenario["kane_objective"],
                "url": scenario["kane_url"],
                "timeout": 180 if scenario["id"] == "SC-003" else 120,
                "max_steps": max_steps,
                "last_run_status": scenario.get("kane_last_status", "not_run"),
                "last_run_date": today if scenario.get("kane_last_status") else None,
            }
        )
    return objectives


def main():
    args = parse_args()
    scenarios = load_scenarios(args.scenarios)

    rendered = [HEADER.rstrip(), ""]
    for scenario in scenarios:
        rendered.append(build_test_function(scenario).rstrip())
        rendered.append("")

    test_output = Path(args.tests_out)
    test_output.parent.mkdir(parents=True, exist_ok=True)
    test_output.write_text("\n".join(rendered).rstrip() + "\n", encoding="utf-8")

    objectives = build_objectives(scenarios)
    objectives_path = Path(args.objectives_out)
    objectives_path.parent.mkdir(parents=True, exist_ok=True)
    objectives_path.write_text(json.dumps(objectives, indent=2) + "\n", encoding="utf-8")

    print(f"tests_generated={len(scenarios)} objectives_updated={len(objectives)}")


if __name__ == "__main__":
    main()
